export const WEB_ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  MASTER: {
    ADMIN_SETUP: "/master/admin-setup",
    MENU_SETUP: "/master/admin-setup/menu-setup",
    COMMON_LISTS: "/master/common-lists",
    RATE_TYPES: "/master/rate-types",
    METALS: "/master/metals",
    INVENTORY: {
      ITEM_GROUPS: "/master/inventory/item-groups",
      ITEMS: "/master/inventory/items",
      ITEM_CODES: "/master/inventory/item-code",
    },
    ACCOUNTS_MANAGEMENT: {
      ACCOUNT_MASTER: "/master/accounts/account-master",
      ACCOUNT_MASTER_ADD: "/master/accounts/account-master/add",
      ACCOUNT_MASTER_EDIT: "/master/accounts/account-master/edit/:id",
    },
    OTHER_MASTER: {
      DAYBOOK_GROUPS: "/master/other-master/daybook-groups",
      DAYBOOKS: "/master/other-master/daybooks",
    },
  },
  TRANSACTION: {
    SALES_LIST: "/transactions/customer-in-out/sales",
    SALES: "/transactions/customer-in-out/sales/:token",
    PURCHASE_LIST: "/transactions/supplier-in-out/purchase",
    PURCHASE: "/transactions/supplier-in-out/purchase/:token",
    PAYMENTS_LIST: "/transactions/payments",
    PAYMENTS: "/transactions/payments/:token",
    CASH_PAYMENT_LIST: "/transactions/payments/cash-payment",
    CASH_PAYMENT: "/transactions/payments/cash-payment/:token",
    RECEIPT_LIST: "/transactions/receipt",
    RECEIPT: "/transactions/receipt/:token",
    CASH_RECEIPT_LIST: "/transactions/receipt/cash-receipt",
    CASH_RECEIPT: "/transactions/receipt/cash-receipt/:token",
  },
};
